"""empty message

Revision ID: 54f00ea17d53
Revises: af739a9cb848
Create Date: 2022-02-28 17:56:26.482156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54f00ea17d53'
down_revision = 'af739a9cb848'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vr_user', sa.Column('public_id', sa.String(length=64), nullable=False))
    op.create_unique_constraint(None, 'vr_user', ['public_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vr_user', type_='unique')
    op.drop_column('vr_user', 'public_id')
    # ### end Alembic commands ###
