"""empty message

Revision ID: dd96b76865ad
Revises: 
Create Date: 2022-02-25 16:42:37.165522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd96b76865ad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vr_customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('email', sa.String(length=30), nullable=False),
    sa.Column('telephone', sa.String(length=10), nullable=False),
    sa.Column('company', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('vr_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=25), nullable=False),
    sa.Column('password_hash', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('vr_vehicle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('cost_per_day', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('penalty_per_day', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('vehicle_type', sa.Enum('saloon', 'bus', 'motor_cycle', 'bicycle', name='vehicletype'), nullable=False),
    sa.Column('rented', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vr_rental',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('proposed_return_date', sa.Date(), nullable=False),
    sa.Column('actual_return_date', sa.Date(), nullable=True),
    sa.Column('actual_charge', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('penalty_charge', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['vr_customer.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vr_vehicle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vr_rental')
    op.drop_table('vr_vehicle')
    op.drop_table('vr_user')
    op.drop_table('vr_customer')
    # ### end Alembic commands ###
